package main

func main() {
	// panic(errors.New("this is an error generated by me, Arinze Obi"))
	// person := struct_lesson.Person{}

	// person.Initiate()
	// person.Greet()
	// person.Clear()
	// person.Greet()
}

// does struct support optional fields?
// answer - no
// instance of a struct
// does struct support default values?
